config/routes.rb
Rails.application.routes.draw do
#PELIS-------------------------------------
  get 'movie/inicio', to: 'movies#index'
  get 'movie/formulario', to: 'movies#new'
  get 'movie/movie_created', to: 'movies#success'
#SERIES-------------------------------------
  get 'serie/inicio', to: 'series#index'
  get 'serie/formulario', to: 'series#new'
  get 'serie/serie_creaded', to: 'series#success'
#DOCUS-------------------------------------
  get 'docu/inicio', to: 'documentaryfilms#index'
  get 'docu/formulario', to: 'documentaryfilms#new'
  get 'docu/docu_created', to: 'documentaryfilms#success'
#-------------------------------------
#POST
  post 'documentaryfilms/create', to: 'documentaryfilms#create'
  post 'series/create', to: 'series#create'
  post 'movies/create', to: 'movies#create'

  root 'overviews#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentaryfilm.rb
class Documentaryfilm < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentaryfilms_controller.rb
class DocumentaryfilmsController < ApplicationController
  def index
    @docu = Documentaryfilm.all()

    render layout: 'layDocu'
  end

  def create
    @docu = Documentaryfilm.new(docu_params)

    if @docu.save
      redirect_to docu_inicio_path
    else
      render :new
    end
  end

  def new
    render layout: 'layDocu'
  end

  def success
    render layout: 'layDocu'
  end

  def docu_params
    params.require(:documentaryfilm).permit(:name, :synopsis, :director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movie = Movie.all()
    
    render layout: 'layMovie'
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movie_inicio_path
    else
      render :new
    end
  end

  def new
    render layout: 'layMovie'
  end

  def success
    render layout: 'layMovie'
  end
  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/overviews_controller.rb
class OverviewsController < ApplicationController
  def index
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @serie = Serie.all()
    render layout: 'laySerie'
  end

  def create
    @serie = Serie.new(serie_params)

    if @serie.save
      redirect_to serie_inicio_path
    else
      render :new #Esto vuelve a renderear la vista asociada al controlador, no olvidar
    end
  end

  def new
    render layout: 'laySerie'
  end

  def success
    render layout: 'laySerie'
  end

  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentaryfilms_helper.rb
module DocumentaryfilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/overviews_helper.rb
module OverviewsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentaryfilms/index.html.erb
<h1>¡Bienvenid@ a la sección de documentales!</h1>
<hr>
<div class="row mt-4">
    <div class="col-6">
        <% @docu.each do |d| %>
            <p class="fw-700 fs-5">Serie n°<%=d.id%></p>
            <p class="fw-300"> <span class="fw-600">Nombre: </span> <%=d.name%></p>
            <p class="fw-300"> <span class="fw-600">Sinopsis: </span> <%=d.synopsis%></p>
            <p class="fw-300"> <span class="fw-600">Director: </span> <%=d.director%></p>
            <hr>
        <%end%>
    </div>
</div>

app/views/documentaryfilms/new.html.erb
<h1>Nuevo Documental</h1>
<p>Ingrese los datos solicitados</p>
<hr>

<%= form_with url: '/../documentaryfilms/create', model:@docu, method: :post do |form| %>
    <div class="col-4">
        <div class="mb-4 mt-4">
            <%= form.label :name, "Nombre", class: "form-label fs-5 fw-300" %>
            <%= form.text_field :name, name: "documentaryfilm[name]", class: "form-control"  %>
        </div>

        <div class="mb-4" >
            <%= form.label :synopsis, "Sinopsis", class: "form-label fs-5 fw-300" %>
            <%= form.text_field :synopsis, name: "documentaryfilm[synopsis]", class: "form-control"%>
        </div>

        <div class="mb-4" >
            <%= form.label :director, "Director", class: "form-label fs-5 fw-300" %>
            <%= form.text_field :director, name: "documentaryfilm[director]", class: "form-control" %>
        </div>

        <div class="mb-4" >
            <%=form.submit "Ingresar", class: "btn btn-light bg-indigo text-snow" %>
        </div>
    </div>
<%end%>

app/views/documentaryfilms/success.html.erb
<h1>Película ingresada correctamente</h1>
<p><%=link_to "Volver a Películas", movie_inicio_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio1M5U3ErickRivera</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/layDocu.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor de Docufilms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="<%= asset_path 'icons/docu/favicon.ico'%>" type="image/x-icon">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark">
      <div class="container-fluid">
        <%=link_to "VideoMyAdmin - Documentales", root_path, class: "navbar-brand title-font text-snow mx-auto fs-4 ruby-link" %>
      </div>
    </nav>
    <nav class="navbar navbar-expand-lg bg-indigo">
      <div class="container-fluid">
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%=link_to "Nuevo Documental", docu_formulario_path, class: "nav-link text-snow fw-400 fs-6 px-3 ruby-link" %>
            </li>
            <li class="nav-item">
              <%=link_to "Ver películas", movie_inicio_path, class: "nav-link text-snow fw-300 fs-6 px-3 ruby-link" %>
            </li>
            <li class="nav-item">
              <%=link_to "Ver series", serie_inicio_path, class: "nav-link text-snow fw-300 fs-6 px-3 ruby-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container my-5"><%= yield %></div>
  </body>
</html>

app/views/layouts/layMovie.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor de Películas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="<%= asset_path 'icons/movie/favicon.ico'%>" type="image/x-icon">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark">
      <div class="container-fluid">
        <%=link_to "VideoMyAdmin - Películas", root_path, class: "navbar-brand title-font text-snow mx-auto fs-4 ruby-link" %>
      </div>
    </nav>
    <nav class="navbar navbar-expand-lg bg-red">
      <div class="container-fluid">
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%=link_to "Nueva Película", movie_formulario_path, class: "nav-link text-snow fw-400 fs-6 px-3 ruby-link" %>
            </li>
            <li class="nav-item">
              <%=link_to "Ver series", serie_inicio_path, class: "nav-link text-snow fw-300 fs-6 px-3 ruby-link" %>
            </li>
            <li class="nav-item">
              <%=link_to "Ver documentales", docu_inicio_path, class: "nav-link text-snow fw-300 fs-6 px-3 ruby-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container my-5"><%= yield %></div>
  </body>
</html>

app/views/layouts/laySerie.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor de Series</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="<%= asset_path 'icons/serie/favicon.ico'%>" type="image/x-icon">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark">
      <div class="container-fluid">
        <%=link_to "VideoMyAdmin - Series", root_path, class: "navbar-brand title-font text-snow mx-auto fs-4 ruby-link" %>
      </div>
    </nav>
    <nav class="navbar navbar-expand-lg bg-orange">
      <div class="container-fluid">
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%=link_to "Nueva Serie", serie_formulario_path, class: "nav-link text-snow fw-400 fs-6 px-3 ruby-link" %>
            </li>
            <li class="nav-item">
              <%=link_to "Ver películas", movie_inicio_path, class: "nav-link text-snow fw-300 fs-6 px-3 ruby-link" %>
            </li>
            <li class="nav-item">
              <%=link_to "Ver documentales", docu_inicio_path, class: "nav-link text-snow fw-300 fs-6 px-3 ruby-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container my-5"><%= yield %></div>
  </body>
</html>

app/views/movies/index.html.erb
<h1>¡Bienvenid@ a la sección de películas!</h1>
<hr>
<div class="row mt-4">
    <div class="col-6">
        <% @movie.each do |m| %>
            <p class="fw-700 fs-5">Película n°<%=m.id%></p>
            <p class="fw-300"> <span class="fw-600">Nombre: </span> <%=m.name%></p>
            <p class="fw-300"> <span class="fw-600">Sinopsis: </span> <%=m.synopsis%></p>
            <p class="fw-300"> <span class="fw-600">Director: </span> <%=m.director%></p>
            <hr>
        <%end%>
    </div>
</div>

app/views/movies/new.html.erb
<h1>Nueva Película</h1>
<p>Ingrese los datos solicitados</p>
<hr>

<%= form_with url: '/../movies/create', model:@movie, method: :post do |form| %>
    <div class="col-4">
        <div class="mb-4 mt-4" >
            <%= form.label :name, "Nombre", class: "form-label fs-5 fw-300" %>
            <%= form.text_field :name, name: "movie[name]", class: "form-control"  %>
        </div>

        <div class="mb-4" >
            <%= form.label :synopsis, "Sinopsis", class: "form-label fs-5 fw-300" %>
            <%= form.text_field :synopsis, name: "movie[synopsis]", class: "form-control"%>
        </div>

        <div class="mb-4" >
            <%= form.label :director, "Director", class: "form-label fs-5 fw-300" %>
            <%= form.text_field :director, name: "movie[director]", class: "form-control" %>
        </div>

        <div class="mb-4" >
            <%=form.submit "Ingresar", class: "btn btn-light bg-red text-snow" %>
        </div>
    </div>
<%end%>

app/views/movies/success.html.erb
<h1>Movies#success</h1>
<p>Find me in app/views/movies/success.html.erb</p>

app/views/overviews/index.html.erb
<p class="fs-5 fw-300">Bievenido al sistema de administración de medios audiovisuales para Inforcap</p>
<div class="row mt-5">
    <div class="col-6">
        <ul class="list-group">
            <li class="list-group-item"><i class="fa-solid fa-circle-chevron-right text-red fs-4 me-3"></i><%=link_to "Directorio Peliculas", movie_inicio_path, class: "text-decoration-none fw-600 text-dark fs-4" %></li>
            <li class="list-group-item"><i class="fa-solid fa-circle-chevron-right text-orange fs-4 me-3"></i><%=link_to "Directorio Series", serie_inicio_path, class: "text-decoration-none fw-600 text-dark fs-4" %></li>
            <li class="list-group-item"><i class="fa-solid fa-circle-chevron-right text-indigo fs-4 me-3"></i><%=link_to "Directorio Documentales", docu_inicio_path, class: "text-decoration-none fw-600 text-dark fs-4" %></li>
        </ul>
    </div>
</div>

app/views/series/index.html.erb
<h1>¡Bienvenid@ a la sección de series!</h1>
<hr>
<div class="row mt-4">
    <div class="col-6">
        <% @serie.each do |s| %>
            <p class="fw-700 fs-5">Serie n°<%=s.id%></p>
            <p class="fw-300"> <span class="fw-600">Nombre: </span> <%=s.name%></p>
            <p class="fw-300"> <span class="fw-600">Sinopsis: </span> <%=s.synopsis%></p>
            <p class="fw-300"> <span class="fw-600">Director: </span> <%=s.director%></p>
            <hr>
        <%end%>
    </div>
</div>

app/views/series/new.html.erb
<h1>Nueva Serie</h1>
<p>Ingrese los datos solicitados</p>
<hr>

<%= form_with url: '/../series/create', model:@serie, method: :post do |form| %>
    <div class="col-4">
        <div class="mb-4 mt-4" >
            <%= form.label :name, "Nombre", class: "form-label fs-5 fw-300" %>
            <%= form.text_field :name, name: "serie[name]", class: "form-control"  %>
        </div>

        <div class="mb-4" >
            <%= form.label :synopsis, "Sinopsis", class: "form-label fs-5 fw-300" %>
            <%= form.text_field :synopsis, name: "serie[synopsis]", class: "form-control"%>
        </div>

        <div class="mb-4" >
            <%= form.label :director, "Director", class: "form-label fs-5 fw-300" %>
            <%= form.text_field :director, name: "serie[director]", class: "form-control" %>
        </div>

        <div class="mb-4" >
            <%=form.submit "Ingresar", class: "btn btn-light bg-orange text-snow" %>
        </div>
    </div>
<%end%>

app/views/series/success.html.erb
<h1>Series#success</h1>
<p>Find me in app/views/series/success.html.erb</p>